# Generated by Django 4.2.11 on 2024-10-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_p', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('peso', models.CharField(max_length=30)),
                ('precio', models.FloatField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
