# Generated by Django 4.2.11 on 2024-10-18 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webprincipal', '0002_categoria_marca_productos_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='categoria',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='nombre_p',
            new_name='nombre',
        ),
    ]
