# Generated by Django 4.2.11 on 2024-10-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webprincipal', '0005_carritoproducto_alter_carrito_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoproducto',
            name='precio',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carritoproducto',
            name='user',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
