# Generated by Django 4.2.11 on 2024-10-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webprincipal', '0007_productos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoproducto',
            name='precioFin',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
