# Generated by Django 4.2.11 on 2024-10-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webprincipal', '0009_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receptor', models.CharField(max_length=20)),
                ('referencia', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=20)),
                ('usuario', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('productos', models.ManyToManyField(to='Webprincipal.productos')),
            ],
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
    ]
