# Generated by Django 4.2.11 on 2024-10-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webprincipal', '0011_alter_ordene_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordene',
            name='productos',
            field=models.ManyToManyField(to='Webprincipal.productos'),
        ),
    ]
