# Generated by Django 4.2.11 on 2024-11-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webprincipal', '0012_alter_ordene_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordene',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=12),
        ),
    ]
