# Generated by Django 4.2.11 on 2024-11-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webprincipal', '0014_categoria_estado_marca_estado_productos_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordene',
            name='total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
